import { ref, computed } from 'vue';

const currentLang = ref(localStorage.getItem('lang') || 'ru');

const translations = {
  ru: {
    tariffs: {
      title: 'Выберите тариф',
      submitTitle: 'Оставить заявку',
      phone: 'Номер телефона',
      selectedPlan: 'Выбранный тариф',
      placeholderPlan: 'Выберите тариф',
      comment: 'Комментарий (необязательно)',
      commentPlaceholder: 'Ваш комментарий или вопрос...',
      submitBtn: 'Отправить заявку',
      sending: 'Отправка...',
      success: 'Заявка успешно отправлена!',
      error: 'Произошла ошибка при отправке заявки',
      selectPlanError: 'Пожалуйста, выберите тариф',
      currency: 'тг',
      plans: {
        math: 'Математика БИЛ-НЗМ',
        logic: 'Логика (БИЛ)',
        bundle: 'БИЛ пакет',
        math5: '5-сынып математика'
      },
      features: {
        access247: '24/7 доступность',
        math53: '53 тақырыптық видео',
        logic20: '20 тақырыптық видео',
        kazakh3: 'Қазақ тілі 3 тақырыптық видео',
        math30: '30 тақырыптық видео',
        test15: 'Әр тақырыпқа 15 сұрақтық тест',
        duration1year: '1 жылға қолжетімділік'
      }
    },
    nav: {
      trial: 'Пробный тест',
      calculator: 'Калькулятор',
      tariffs: 'Тарифы',
      login: 'Войти',
      cabinet: 'Мой кабинет',
      logout: 'Выйти'
    },
    landing: {
      heroTitle: 'Образование Будущего',
      heroSub: 'Учитесь, развивайтесь и достигайте новых высот с нашей платформой.',
      startBtn: 'Начать Обучение',
      whyUs: 'Почему мы?',
      videoTitle: 'Видео Курсы',
      videoSub: 'Доступ к качественным видеоурокам от лучших преподавателей.',
      testTitle: 'Интерактивные Тесты',
      testSub: 'Проверяйте свои знания и отслеживайте прогресс в реальном времени.',
      cabinetTitle: 'Удобный Кабинет',
      cabinetSub: 'Все материалы и статистика в одном месте, доступные 24/7.',
      footerTagline: 'Ваш путь к успеху в образовании.',
      footerQuality: 'Качественная подготовка к НИШ и БИЛ.',
      usefulLinks: 'Полезные ссылки',
      offer: 'Публичная оферта',
      contacts: 'Контакты',
      rights: 'Все права защищены.'
    },
    calculator: {
      title: 'Калькулятор',
      subtitle: 'С этим результатом куда я могу поступить на грант?',
      nzm: 'НИШ',
      bil: 'БИЛ',
      mathematics: 'Математика (400)',
      numericalCharacteristics: 'Числовые хар-ки (300)',
      naturalScience: 'Естествознание (200)',
      kazakh: 'Казахский язык (200)',
      russian: 'Русский язык (200)',
      english: 'Английский язык (200)',
      enterScore: 'Балл',
      check: 'Проверить',
      clear: 'Очистить',
      results: 'Результаты расчета',
      totalScore: 'Общий балл',
      availableSchools: 'Доступно школ',
      from: 'из',
      enterScores: 'Введите ваши баллы',
      fillForm: 'Заполните форму для расчета вероятности поступления',
      school: 'Школа',
      percentage: 'Вероятность',
      bilScore: 'Балл БИЛ',
      enterBilScore: 'Введите ваш балл БИЛ'
    },
    trial: {
      title: 'Пробный Тест',
      description: 'Хотите проверить свои силы перед покупкой курса? Наш пробный тест поможет вам оценить ваш текущий уровень знаний и познакомиться с форматом обучения.',
      duration: '20 минут',
      questions: '15 вопросов',
      result: 'Мгновенный результат',
      ready: 'Готовы начать?',
      startBtn: 'Начать Бесплатно',
      developing: 'Пробный тест находится в разработке.'
    },
    login: {
      title: 'Вход в систему',
      username: 'Логин',
      password: 'Пароль',
      usernamePlaceholder: 'Введите логин',
      passwordPlaceholder: 'Введите пароль',
      submitBtn: 'Войти',
      error: 'Неверный логин или пароль',
      backToHome: 'На главную'
    },
    dashboard: {
      myCourses: 'Мои Курсы',
      testing: 'Тестирование',
      results: 'Результаты',
      trial: 'Пробный тест',
      logout: 'Выйти',
      availableTests: 'Доступные Тесты',
      myProgress: 'Мой Прогресс',
      startBtn: 'Начать',
      backToCourses: 'Вернуться к курсам',
      backToLessons: 'Ко всем урокам',
      hideLessons: 'Скрыть уроки',
      showLessons: 'Список уроков',
      videoReview: 'Видео Разбор',
      lockedReview: 'Разбор (Пройдите тест)',
      startTest: 'Пройти тест',
      score: 'Балл',
      date: 'Дата',
      buyTest: 'Купить за {price} монет',
      owned: 'Куплено',
      notEnoughCoins: 'Недостаточно монет'
    },
    admin: {
      courses: 'Курсы',
      tests: 'Тесты',
      users: 'Пользователи',
      results: 'Результаты',
      welcome: 'Добро пожаловать',
      role: {
        admin: 'Админ',
        teacher: 'Учитель',
        student: 'Ученик'
      },
      userManagement: {
        title: 'Управление Пользователями',
        search: 'Поиск по логину...',
        addBtn: 'Добавить',
        thLogin: 'Логин',
        thRole: 'Роль',
        thActions: 'Действия',
        accessBtn: 'Доступы',
        deleteBtn: 'Удалить',
        newTitle: 'Новый Пользователь',
        loginLabel: 'Логин',
        passwordLabel: 'Пароль',
        roleLabel: 'Роль',
        createBtn: 'Создать',
        cancelBtn: 'Отмена',
        accessTitle: 'Доступы',
        coursesTitle: 'Курсы',
        testsTitle: 'Отдельные Тесты',
        noCourses: 'Нет доступных курсов',
        noTests: 'Нет отдельных тестов',
        saveBtn: 'Сохранить',
        successCreated: 'Пользователь создан!',
        successAccess: 'Доступы обновлены!',
        confirmDelete: 'Удалить пользователя'
      },
      resultsView: {
        title: 'Результаты Тестирования',
        thStudent: 'Ученик',
        thTest: 'Тест',
        thType: 'Тип',
        thScore: 'Баллы',
        thDate: 'Дата',
        unknownUser: 'Неизвестно',
        deletedTest: 'Удаленный тест'
      },
      testRunner: {
        completed: 'Тест Завершен!',
        yourResult: 'Ваш результат:',
        excellent: 'Отличная работа! 🎉',
        good: 'Хороший результат! 👍',
        improve: 'Можно лучше! 💪',
        backToStandalone: 'Вернуться к списку',
        backToLesson: 'Вернуться к уроку',
        question: 'Вопрос',
        finishBtn: 'Завершить Тест',
        error: 'Ошибка',
        scoringBIL: 'Система BIL: правильно (+4), ошибка (-1), пропуск (0)',
        earnedCoins: 'Вы заработали {coins} монет!'
      },
      testManagement: {
        title: 'Управление Тестами',
        newBtn: 'Новый Тест',
        editBtn: 'Редактировать',
        deleteBtn: 'Удалить',
        noDescription: 'Нет описания',
        noTimer: 'Без таймера',
        minutes: 'мин',
        createTitle: 'Создание Теста',
        editTitle: 'Редактирование Теста',
        testName: 'Название теста',
        timeLimit: 'Время (минут)',
        descriptionLabel: 'Описание (опционально)',
        categoryLabel: 'Категория теста',
        categoryStandard: 'Стандарт (+1 за ответ)',
        categoryBIL: 'БИЛ (+4 / -1 / 0)',
        questionsCount: 'Вопросы',
        removeQuestion: 'Удалить вопрос',
        enterQuestion: 'Введите текст вопроса',
        addPhoto: '📷 Добавить фото',
        replacePhoto: '🔄 Заменить фото',
        variant: 'Вариант',
        addQuestion: 'Добавить новый вопрос',
        cancel: 'Отмена',
        save: 'Сохранить Тест',
        successCreated: 'Тест создан!',
        successUpdated: 'Тест обновлен!',
        successDeleted: 'Тест удален',
        confirmDelete: 'Вы уверены, что хотите удалить тест',
        isTrial: 'Пробный тест (общедоступный)',
        trialTag: 'ПРОБНЫЙ',
        coinPrice: 'Цена (монеты)'
      },
      courseManagement: {
        title: 'Курсы и Контент',
        newCourseBtn: 'Новый Курс',
        manageBtn: 'Управление',
        deleteBtn: 'Удалить',
        noDescription: 'Нет описания',
        createTitle: 'Создание Курса',
        courseName: 'Название Курса',
        description: 'Описание',
        createBtn: 'Создать Курс',
        infoTitle: 'Информация',
        editCourseTitle: 'Редактировать курс',
        lessonsCount: 'Уроков',
        lessonsList: 'Список Уроков',
        addLessonBtn: 'Добавить Видео-Урок',
        noLessons: 'В этом курсе пока нет уроков.',
        lessonIcon: '🎥',
        editLesson: 'Изменить',
        deleteLesson: 'Удалить',
        testAttached: 'Тест прикреплен',
        changeTest: 'Изменить тест',
        deleteTest: 'Удалить тест',
        createTest: 'Создать Тест',
        newLessonTitle: 'Новый Урок',
        editLessonTitle: 'Редактирование Урока',
        lessonName: 'Название Урока',
        videoLessons: 'Видео уроки',
        solutions: 'Разборы (доступно после сдачи)',
        addMoreVideo: 'Еще видео',
        addMoreSolution: 'Еще разбор',
        saveChanges: 'Сохранить изменения',
        addLessonAction: 'Добавить Урок',
        testToLesson: 'Тест к уроку',
        editTestToLesson: 'Редактирование теста',
        testName: 'Название Теста',
        timer: 'Таймер (мин)',
        noTimer: 'Без лимита',
        questions: 'Вопросы',
        addQuestion: 'Добавить вопрос',
        photo: 'Фото',
        saveTest: 'Сохранить Тест',
        successCourseCreated: 'Курс создан!',
        successCourseUpdated: 'Курс обновлен!',
        successCourseDeleted: 'Курс удален!',
        successLessonAdded: 'Урок добавлен!',
        successLessonUpdated: 'Урок обновлен!',
        successLessonDeleted: 'Урок удален!',
        successTestCreated: 'Тест создан!',
        successTestUpdated: 'Тест обновлен!',
        successTestDeleted: 'Тест удален!',
        successPhotoUploaded: 'Фото загружено!',
        confirmDeleteCourse: 'Вы уверены, что хотите удалить курс? Это действие необратимо.',
        confirmDeleteLesson: 'Удалить этот урок?',
        confirmDeleteTest: 'Вы уверены, что хотите удалить этот тест?'
      },
      trial: {
        title: 'Пробный тест',
        description: 'Оцените свои знания прямо сейчас! Пройдите ознакомительный тест в формате НИШ/РФМШ бесплатно.',
        duration: '15 минут',
        questions: '10-20 вопросов',
        result: 'Мгновенный результат',
        ready: 'Готовы начать?',
        startBtn: 'Начать тест бесплатно',
        developing: 'Тест загружается...'
      }
    }
  },
  kk: {
    tariffs: {
      title: 'Тарифті таңдаңыз',
      submitTitle: 'Өтінім қалдыру',
      phone: 'Телефон нөмірі',
      selectedPlan: 'Таңдалған тариф',
      placeholderPlan: 'Тарифті таңдаңыз',
      comment: 'Пікір (міндетті емес)',
      commentPlaceholder: 'Пікіріңіз немесе сұрағыңыз...',
      submitBtn: 'Өтінімді жіберу',
      sending: 'Жіберілуде...',
      success: 'Өтінім сәтті жіберілді!',
      error: 'Өтінім жіберу кезінде қате кетті',
      selectPlanError: 'Тарифті таңдаңыз',
      currency: 'тг',
      plans: {
        math: 'Математика БИЛ-НЗМ',
        logic: 'Логика (БИЛ)',
        bundle: 'БИЛ пакет',
        math5: '5-сынып математика'
      },
      features: {
        access247: '24/7 қолжетімділік',
        math53: '53 тақырыптық видео',
        logic20: '20 тақырыптық видео',
        kazakh3: 'Қазақ тілі 3 тақырыптық видео',
        math30: '30 тақырыптық видео',
        test15: 'Әр тақырыпқа 15 сұрақтық тест',
        duration1year: '1 жылға қолжетімділік'
      }
    },
    nav: {
      trial: 'Пробный тест',
      calculator: 'Калькулятор',
      tariffs: 'Тарифтер',
      login: 'Кіру',
      cabinet: 'Жеке кабинет',
      logout: 'Шығу'
    },
    landing: {
      heroTitle: 'Болашақ Білімі',
      heroSub: 'Біздің платформамызбен бірге білім алыңыз, дамыңыз және жаңа белестерді бағындырыңыз.',
      startBtn: 'Оқуды бастау',
      whyUs: 'Неліктен біз?',
      videoTitle: 'Видео курстар',
      videoSub: 'Үздік мұғалімдердің сапалы видеосабақтарына қол жеткізіңіз.',
      testTitle: 'Интерактивті тесттер',
      testSub: 'Біліміңізді тексеріп, үлгеріміңізді нақты уақыт режимінде бақылаңыз.',
      cabinetTitle: 'Ыңғайлы кабинет',
      cabinetSub: 'Барлық материалдар мен статистика бір жерде, 24/7 қолжетімді.',
      footerTagline: 'Білімдегі табысқа жетелер жолыңыз.',
      footerQuality: 'НЗМ және БИЛ-ге сапалы дайындық.',
      usefulLinks: 'Пайдалы сілтемелер',
      offer: 'Жария оферта',
      contacts: 'Контактілер',
      rights: 'Барлық құқықтар қорғалған.'
    },
    calculator: {
      title: 'Калькулятор',
      subtitle: 'Осы нәтижеммен қайда грантқа түсе аламын?',
      nzm: 'НИШ',
      bil: 'БИЛ',
      mathematics: 'Математика (400)',
      numericalCharacteristics: 'Сандық сипаттамалар (300)',
      naturalScience: 'Жаратылыстану (200)',
      kazakh: 'Қазақ тілі (200)',
      russian: 'Орыс тілі (200)',
      english: 'Ағылшын тілі (200)',
      enterScore: 'Балл',
      check: 'Тексеру',
      clear: 'Тазалау',
      results: 'Есептеу нәтижелері',
      totalScore: 'Жалпы балл',
      availableSchools: 'Қолжетімді мектептер',
      from: 'дан',
      enterScores: 'Баллдарыңызды енгізіңіз',
      fillForm: 'Түсу ықтималдығын есептеу үшін форманы толтырыңыз',
      school: 'Мектеп',
      percentage: 'Ықтималдық',
      bilScore: 'БИЛ баллы',
      enterBilScore: 'БИЛ баллыңызды енгізіңіз'
    },
    trial: {
      title: 'Сынақ тесті',
      description: 'Курсты сатып алмас бұрын өз күшіңізді тексергіңіз келе ме? Біздің сынақ тестіміз қазіргі білім деңгейіңізді бағалауға және оқыту форматымен танысуға көмектеседі.',
      duration: '20 минут',
      questions: '15 сұрақ',
      result: 'Жылдам нәтиже',
      ready: 'Бастауға дайынсыз ба?',
      startBtn: 'Тегін бастау',
      developing: 'Сынақ тесті әлі жасалып жатыр.'
    },
    login: {
      title: 'Жүйеге кіру',
      username: 'Логин',
      password: 'Құпия сөз',
      usernamePlaceholder: 'Логинді енгізіңіз',
      passwordPlaceholder: 'Құпия сөзді енгізіңіз',
      submitBtn: 'Кіру',
      error: 'Логин немесе құпия сөз қате',
      backToHome: 'Басты бетке'
    },
    dashboard: {
      myCourses: 'Менің курстарым',
      testing: 'Тестілеу',
      results: 'Нәтижелер',
      trial: 'Сынақ тесті',
      logout: 'Шығу',
      availableTests: 'Қолжетімді тесттер',
      myProgress: 'Менің үлгерімім',
      startBtn: 'Бастау',
      backToCourses: 'Курстарға оралу',
      backToLessons: 'Барлық сабақтарға',
      hideLessons: 'Сабақтарды жасыру',
      showLessons: 'Сабақтар тізімі',
      videoReview: 'Видео талдау',
      lockedReview: 'Талдау (Тест тапсырыңыз)',
      startTest: 'Тест тапсыру',
      score: 'Балл',
      date: 'Күні',
      buyTest: '{price} монетаға сатып алу',
      owned: 'Сатып алынған',
      notEnoughCoins: 'Монеталар жеткіліксіз'
    },
    admin: {
      courses: 'Курстар',
      tests: 'Тесттер',
      users: 'Пайдаланушылар',
      results: 'Нәтижелер',
      welcome: 'Қош келдіңіз',
      role: {
        admin: 'Админ',
        teacher: 'Мұғалім',
        student: 'Оқушы'
      },
      userManagement: {
        title: 'Пайдаланушыларды басқару',
        search: 'Логин бойынша іздеу...',
        addBtn: 'Қосу',
        thLogin: 'Логин',
        thRole: 'Роль',
        thActions: 'Әрекеттер',
        accessBtn: 'Рұқсаттар',
        deleteBtn: 'Жою',
        newTitle: 'Жаңа пайдаланушы',
        loginLabel: 'Логин',
        passwordLabel: 'Құпия сөз',
        roleLabel: 'Роль',
        createBtn: 'Жасау',
        cancelBtn: 'Бас тарту',
        accessTitle: 'Рұқсаттар',
        coursesTitle: 'Курстар',
        testsTitle: 'Жеке тесттер',
        noCourses: 'Қолжетімді курстар жоқ',
        noTests: 'Жеке тесттер жоқ',
        saveBtn: 'Сақтау',
        successCreated: 'Пайдаланушы жасалды!',
        successAccess: 'Рұқсаттар жаңартылды!',
        confirmDelete: 'Пайдаланушыны жою'
      },
      resultsView: {
        title: 'Тест нәтижелері',
        thStudent: 'Оқушы',
        thTest: 'Тест',
        thType: 'Түрі',
        thScore: 'Ұпай',
        thDate: 'Күні',
        unknownUser: 'Белгісіз',
        deletedTest: 'Жойылған тест'
      },
      testRunner: {
        completed: 'Тест аяқталды!',
        yourResult: 'Сіздің нәтижеңіз:',
        excellent: 'Өте жақсы жұмыс! 🎉',
        good: 'Жақсы нәтиже! 👍',
        improve: 'Жақсырақ болуы мүмкін! 💪',
        backToStandalone: 'Тізімге оралу',
        backToLesson: 'Сабаққа оралу',
        question: 'Сұрақ',
        finishBtn: 'Тестті аяқтау',
        error: 'Қате',
        scoringBIL: 'BIL жүйесі: дұрыс (+4), қате (-1), белгіленбеген (0)',
        earnedCoins: 'Сіз {coins} монета таптыңыз!'
      },
      testManagement: {
        title: 'Тесттерді басқару',
        newBtn: 'Жаңа тест',
        editBtn: 'Өңдеу',
        deleteBtn: 'Жою',
        noDescription: 'Сипаттамасы жоқ',
        noTimer: 'Таймерсіз',
        minutes: 'мин',
        createTitle: 'Тест жасау',
        editTitle: 'Тестті өңдеу',
        testName: 'Тест атауы',
        timeLimit: 'Уақыт (минут)',
        descriptionLabel: 'Сипаттама (міндетті емес)',
        categoryLabel: 'Тест санаты',
        categoryStandard: 'Стандарт (+1 жауап үшін)',
        categoryBIL: 'БИЛ (+4 / -1 / 0)',
        questionsCount: 'Сұрақтар',
        removeQuestion: 'Сұрақты жою',
        enterQuestion: 'Сұрақ мәтінін енгізіңіз',
        addPhoto: '📷 Сурет қосу',
        replacePhoto: '🔄 Суретті ауыстыру',
        variant: 'Нұсқа',
        addQuestion: 'Жаңа сұрақ қосу',
        cancel: 'Бас тарту',
        save: 'Тестті сақтау',
        successCreated: 'Тест жасалды!',
        successUpdated: 'Тест жаңартылды!',
        successDeleted: 'Тест жойылды',
        confirmDelete: 'Тестті жойғыңыз келетініне сенімдісіз бе',
        isTrial: 'Пробты тест (бәріне қолжетімді)',
        trialTag: 'ПРОБТЫ',
        coinPrice: 'Бағасы (монета)'
      },
      courseManagement: {
        title: 'Курстар мен мазмұн',
        newCourseBtn: 'Жаңа курс',
        manageBtn: 'Басқару',
        deleteBtn: 'Жою',
        noDescription: 'Сипаттамасы жоқ',
        createTitle: 'Курс жасау',
        courseName: 'Курс атауы',
        description: 'Сипаттама',
        createBtn: 'Курсты жасау',
        infoTitle: 'Ақпарат',
        editCourseTitle: 'Курсты өңдеу',
        lessonsCount: 'Сабақтар',
        lessonsList: 'Сабақтар тізімі',
        addLessonBtn: 'Видео-сабақ қосу',
        noLessons: 'Бұл курста әзірге сабақтар жоқ.',
        lessonIcon: '🎥',
        editLesson: 'Өзгерту',
        deleteLesson: 'Жою',
        testAttached: 'Тест қосылған',
        changeTest: 'Тестті өзгерту',
        deleteTest: 'Тестті жою',
        createTest: 'Тест жасау',
        newLessonTitle: 'Жаңа сабақ',
        editLessonTitle: 'Сабақты өңдеу',
        lessonName: 'Сабақ атауы',
        videoLessons: 'Видео сабақтар',
        solutions: 'Талдаулар (тапсырғаннан кейін қол жетімді)',
        addMoreVideo: 'Тағы видео',
        addMoreSolution: 'Тағы талдау',
        saveChanges: 'Өзгерістерді сақтау',
        addLessonAction: 'Сабақ қосу',
        testToLesson: 'Сабаққа арналған тест',
        editTestToLesson: 'Тестті өңдеу',
        testName: 'Тест атауы',
        timer: 'Таймер (мин)',
        noTimer: 'Шектеусіз',
        questions: 'Сұрақтар',
        addQuestion: 'Сұрақ қосу',
        photo: 'Сурет',
        saveTest: 'Тестті сақтау',
        successCourseCreated: 'Курс жасалды!',
        successCourseUpdated: 'Курс жаңартылды!',
        successCourseDeleted: 'Курс жойылды!',
        successLessonAdded: 'Сабақ қосылды!',
        successLessonUpdated: 'Сабақ жаңартылды!',
        successLessonDeleted: 'Сабақ жойылды!',
        successTestCreated: 'Тест жасалды!',
        successTestUpdated: 'Тест жаңартылды!',
        successTestDeleted: 'Тест жойылды!',
        successPhotoUploaded: 'Сурет жүктелді!',
        confirmDeleteCourse: 'Бұл курсты жойғыңыз келетініне сенімдісіз бе? Бұл әрекетті қайтару мүмкін емес.',
        confirmDeleteLesson: 'Бұл сабақты жою керек пе?',
        confirmDeleteTest: 'Бұл тестті жойғыңыз келетініне сенімдісіз бе?'
      },
      trial: {
        title: 'Пробты тест',
        description: 'Өз біліміңізді дәл қазір тексеріңіз! ЗТМ/РФММ форматындағы таныстыру тестін тегін тапсырыңыз.',
        duration: '15 минут',
        questions: '10-20 сұрақ',
        result: 'Жылдам нәтиже',
        ready: 'Бастауға дайынсыз ба?',
        startBtn: 'Тестті тегін бастау',
        developing: 'Тест жүктелуде...'
      }
    }
  }
};

export function useLanguage() {
  const setLanguage = (lang) => {
    currentLang.value = lang;
    localStorage.setItem('lang', lang);
  };

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[currentLang.value];
    for (const k of keys) {
      if (value) value = value[k];
      else return key;
    }
    return value || key;
  };

  const format = (text, params) => {
    let result = text;
    for (const [key, value] of Object.entries(params)) {
      result = result.replace(`{${key}}`, value);
    }
    return result;
  };

  return {
    currentLang,
    setLanguage,
    t,
    format
  };
}
